### ISSUE TITLE
Character-Count bei Titel und Excerpt

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#23]
Bei der Eingabe von Titel und Excerpt kommt es immer wieder vor, dass wir zu lange sind. Das soll nciht verhindert werden, weil evtl. geht es manchmal einfach nicht anders, aber zumindest sollte das der Autor checken.

Also hier am besten einen Zähler mitlaufen lassen, der von 30 (bei Titel) oder xy bei Exceprt runterzählt:
![screen shot 2014-11-20 at 16 29 56](https://cloud.githubusercontent.com/assets/7487883/5127140/843eaf00-70d2-11e4-9c9c-14ddc22003c9.png)
![screen shot 2014-11-20 at 16 30 00](https://cloud.githubusercontent.com/assets/7487883/5127145/89d01f4e-70d2-11e4-96cd-b75f024e37ce.png)
Einfach drunter - nicht zu aggro.

**Comment by KennySchnett** [comment]
Der Counter is eingefügt (wieder erstmal auf dem develop git).
Wär cool wenn wir wieder einen "ready for live" tag/label hätten ;-)
