### ISSUE TITLE
Suche findet Artikel nicht

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#24]
Ich habe einen bestimmten rtikel gesucht auf geo365.no, aber nicht gefunden.

Suchwörter:
"Four finalists – four talents: Meet tor"

Auf geo365.no kein Ergebnis (der Link, der angegeben wird ist nutzlos):
![screen shot 2014-11-24 at 09 13 09](https://cloud.githubusercontent.com/assets/7487883/5162098/2b0d339e-73ba-11e4-96d3-e01fa5c827f0.png)

Auf Google findet der den:
![screen shot 2014-11-24 at 09 12 51](https://cloud.githubusercontent.com/assets/7487883/5162100/2e865fe6-73ba-11e4-8133-a8c7a6128b8d.png)

Da ist scheints Optimierungspotential...

**Comment by diplomod** [comment]
Das ist sicher ein Thema, bei dem @chrwhm noch unterstützen muss bei Gelegenheit

**Comment by KennySchnett** [comment]
Liegt sicher an dem Delay zwischen dem "echten" Google und der eingebauten Google-Suche. Inzwischen kann ich diesen Artikel nämlich auch mit der GEO365 Suche finden. Ich glaube Google verzögert bei solchen eingebundenen Suchen die Aktuellsten Ergebnisse ein paar Minuten/Stunden, um selbst immer der Aktuellste zu sein. Ist aber auch verständlich, immerhin bekommen wir die SuFu kostenlos von denen :-)
Ist also eventuell keine Änderung nötig...

**Comment by diplomod** [comment]
Verstehe - alles klar, passt. Ich fidne jetzt auch alles. Merci. Guter Einstand in dem Projekt ;)
