### ISSUE TITLE
Update Wordpress

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#46]
Ich schlage vor, wir machen das mal, oder?

![screen shot 2015-01-16 at 12 12 23](https://cloud.githubusercontent.com/assets/7487883/5775335/f6e7a5c0-9d78-11e4-98ca-b9ae0fea1e96.png)

**Comment by chrwhm** [comment]
Erledigt.

**Comment by diplomod** [comment]
Danke - scheint ja kein riesen Act gewese zu sein. Und auf der Live geht auch noch alles. Nur finde ich schade, dass keine neuen Megafeatures ins Auge springen... :)
