### ISSUE TITLE
Quick fix: Right Column in Mediaplan

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#47]
Diese Ausklappfunktion ist komplett für die Katz - bitte das "Information for advertisers" raus und Überschrift "ONLINE MEDIA AND RATES" wie in der linken Spalte.
Kein Aufklappen mehr.
![screen shot 2015-01-16 at 12 58 21](https://cloud.githubusercontent.com/assets/7487883/5775816/8ee9b416-9d7f-11e4-9402-e2dc4817d70b.png)

**Comment by chrwhm** [comment]
Ist erstmal drin

**Comment by diplomod** [comment]
Super - anst noch den grauen Balken raushauen?
![screen shot 2015-01-19 at 16 58 41](https://cloud.githubusercontent.com/assets/7487883/5803187/85b59232-9ffc-11e4-8757-1718486aa9b0.png)
