### ISSUE TITLE
SPAM Ads

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#48]
Hilfe - was ist da los? 
Browser aktualisieren oder Virenscanner? Oder ist das auf geo365 irgendwo?

![screenshot 2015-01-18 20 29 20](https://cloud.githubusercontent.com/assets/7487883/5793948/7df3d02a-9f59-11e4-9b91-6281fa114d9c.png)

**Comment by chrwhm** [comment]
Habe jetzt im Büro auch nochmal mit unserem Windows-Testrechner probiert und keine Anhaltspunkte für derartiges feststellen können. Würde es daher auf den PC schieben ;-)

**Comment by diplomod** [comment]
merci - hab ich mir schon gedacht
