### ISSUE TITLE
Banners - komische Posts in Banner Areas

### ISSUE THREAD

**Issue by diplomod** [diplomod/geo365#51]
??

![screen shot 2015-03-26 at 15 58 05](https://cloud.githubusercontent.com/assets/7487883/6849060/fe765e38-d3d0-11e4-8bfc-774d7311ae13.png)

**Comment by diplomod** [comment]
Verlinken der Posts mit Magazinen funktioniert ebenfalls nicht mehr - gleiches Problem

**Comment by chrwhm** [comment]
sollte jetzt wieder passen - Auswahl findet jetzt über ein klassisches Drop-Down statt.

**Comment by diplomod** [comment]
Super, merci!
